### ISSUE TITLE
Video keeps on running in the background even after closing the video player.

### ISSUE THREAD

**Issue by vikasr111** [montecruiseto/scopemount#1]
I love this theme and started experimenting with it. When I click on the thumbnail the video player opens up in the lightbox. When I close the lightbox by clicking on cross button, the video still keeps on playing in the background as I can hear the audio. This situation becomes even worse when I close one video and click on another video to play - In this case both the apparently videos keeps on playing together.

**Comment by montecruiseto** [comment]
this is a telescope issue, we should probably post that there or ask in the tele Slack

**Comment by vikasr111** [comment]
Sure then let's raise it in Telescope slack group.
