### ISSUE TITLE
How to show post excerpt on each of the post listings (on homepage). [Gemini Theme]

### ISSUE THREAD

**Issue by JamesGibsonUK** [montecruiseto/scopemount#13]
Sorry if you don't provide this kind of support here, but I'm new and would like to learn how to implement this feature.

On the Gemini theme, I want to be able to display a short excerpt of the post's content on its listing on the home page. Is this possible? Is there a template/module that I can call to do this? 

Thanks,

James

**Comment by montecruiseto** [comment]
see #8
