### ISSUE TITLE
Removing Magellan's 'sponsored by' block

### ISSUE THREAD

**Issue by jschuur** [montecruiseto/scopemount#2]
I noticed Magellan has a sponsor block in the sidebar. Is there a good way to remove this, without diving into the innards? I keep my site checked into git, but ignore .meteor/local (as is the default).

Appreciate all the great free themes you guys have been producing BTW. I didn't notice the same insert in other themes. Are you OK with us removing it?

**Comment by jschuur** [comment]
Answering my own question, from the site, if you copy the telescope-theme-sm-magellan directory into a 'packages' subdirectory of your site and run the usual `meteor add montecruiseto:telescope-theme-sm-magellan` command, it uses the local contents from the packages subdirectory. Just to be safe, I removed the package before re-adding it.

`sponsor_magellan.html` was referenced in `package.js`, where I commented it out, which removed the insert. There was another reference in `modules_magellan.js`, which I also removed, although it already worked with just the first change (presumably the latter suppresses an internal error once the former template is undefined).

It works, but now I have to remember to update the Magellan theme manually in the future, should that ever change. Is there a more elegant solution?

**Comment by montecruiseto** [comment]
Thanks @jschuur. What I would do is create a new custom package for my modifications. In that custom package you can call the template with empty contents or remove the template from `modules.js`. That way you will always have the override no matter what updates to the theme (expect file name changes).
