### ISSUE TITLE
Broken Stylesheet

### ISSUE THREAD

**Issue by claudiojulioferraz** [montecruiseto/scopemount#3]
Hello! The post_item is a broken stylesheet. I'm trying to detect the problem, but it's difficult because I'm learning to program. I'll keep trying.

This message has been automatically translated.

![problem](https://cloud.githubusercontent.com/assets/7096023/8685445/051c52d0-2a55-11e5-86af-8468c3b16069.png)

**Comment by sukritchopra** [comment]
I'm facing the same issue with this. Is there any solution?

**Comment by montecruiseto** [comment]
what version of Telescope are you using?
The theme is only compatible with >v0.20

**Comment by claudiojulioferraz** [comment]
I'm using the latest: _v0.21.1_. For some reason the Random Color is not leaking to the `.post` class.

**Comment by sukritchopra** [comment]
I'm on 0.21.

**Comment by montecruiseto** [comment]
ah I noticed that the install does not automatically remove hubble,
so you need to `meteor remove telescope:theme-hubble`
Will add to the docs tomorrow

**Comment by claudiojulioferraz** [comment]
It is working perfectly. And here I am racking my brain :) Thanks a lot!

Using Google Translate.

**Comment by montecruiseto** [comment]
yeah, that one was not easy to debug if you didn't know the theme was not dependent on hubble
