### ISSUE TITLE
Blank screen with Magellan

### ISSUE THREAD

**Issue by rodclarke** [montecruiseto/scopemount#6]
HI I twittered you before - still getting a blank screen w the magellan theme after checking the packages file

**Comment by rodclarke** [comment]
Before

![screenshot from 2015-07-28 20 33 29](https://cloud.githubusercontent.com/assets/13513496/8929346/1192f4ec-3568-11e5-81f7-871f7d430a9d.png)

**Comment by rodclarke** [comment]
After running meteor add montecruiseto:telescope-theme-sm-magellan
![screenshot from 2015-07-28 20 36 42](https://cloud.githubusercontent.com/assets/13513496/8929389/62ac3c8a-3568-11e5-820c-83e741bc51bf.png)

**Comment by montecruiseto** [comment]
perhaps as a result of the latest Telescope update from yesterday? I havent had a chance to look at it, maybe it broke some templates for the themes...... @SachaG moves fast ;-)

**Comment by rodclarke** [comment]
ok thanks - I can get Galileo working o.k. - but I really wan this one - love your work!

**Comment by rodclarke** [comment]
Hi @montecruiseto any update on this please? Much apprieciated!

**Comment by montecruiseto** [comment]
I updated yesterday, can you try again?

**Comment by rodclarke** [comment]
Hi Still getting the blank screen - see terminal with firefox in the background

Screenshot from 2015-08-02 17:48:16

**Comment by rodclarke** [comment]
![running gallileo](https://cloud.githubusercontent.com/assets/13513496/9029025/df1661a0-39ce-11e5-9a38-ca88f88d9fe8.jpg)

**Comment by rodclarke** [comment]
running Magellan
![running magellan](https://cloud.githubusercontent.com/assets/13513496/9029066/bb22d566-39cf-11e5-8e8c-8f3b9ff7c801.jpg)

**Comment by rodclarke** [comment]
I have gotten the same results on stand alone (i.e. not VM)  ubuntu box this morning

**Comment by montecruiseto** [comment]
can you post the contents of your project packages file? 
E.g https://gist.github.com/montecruiseto/09edab2cc3f9ad805fef

**Comment by rodclarke** [comment]
hi here it is 

https://gist.github.com/rodclarke/fcc8b379a85572c08166 

thanks for your help

**Comment by montecruiseto** [comment]
found a bug in the layout template,
pushed a fix just now. Can you try again?

**Comment by rodclarke** [comment]
All fixed - thanks very much !

**Comment by montecruiseto** [comment]
welcome!

**Comment by heyjerrybecker** [comment]
I'm still getting the same issue - saw your tweet and read this thread. Tried removing all theme packets and reinstalling magellan - still a blank screen.

**Comment by SachaG** [comment]
@beckerjs @montecruiseto anything I can do to help?

**Comment by Samirbekaert** [comment]
@beckerjs weird, I got it working on a new install.
Can you check your console if there's any error?
ps have you tried `meteor update`?

**Comment by montecruiseto** [comment]
@beckerjs weird, I got it working on a new install.
Can you check your console if there's any error?
ps have you tried `meteor update`?

**Comment by heyjerrybecker** [comment]
I did the meteor update last night and tried installing the theme just after.
I'll check for console errors

**Comment by montecruiseto** [comment]
I dont know when that was but I pushed the update about 20 hours ago...so maybe try a fresh install?

**Comment by heyjerrybecker** [comment]
Just tried, but no dice. 

Any thoughts?

Regards,
Jerry Becker

**Comment by montecruiseto** [comment]
anything in the console?

**Comment by heyjerrybecker** [comment]
Nope. Everything seems up check out. 

Thanks for the quick replies btw

**Comment by montecruiseto** [comment]
so I just did another completely fresh install

`git clone git@github.com:TelescopeJS/Telescope.git`

then 

`meteor update`

(updates Meteor to 1.1.0.3. and several other packages upgraded)

then

`meteor`

I get this

![screen shot 2015-08-04 at 17 15 09](https://cloud.githubusercontent.com/assets/10129398/9058761/069087b0-3ace-11e5-8eeb-c1eaec1657e3.png)

then 

`meteor add montecruiseto:telescope-theme-sm-magellan`

I get this

![screen shot 2015-08-04 at 17 56 10](https://cloud.githubusercontent.com/assets/10129398/9059194/24ff2e46-3ad2-11e5-9737-3337bff363c1.png)

so it works on my end

**Comment by heyjerrybecker** [comment]
Awesome. Thanks, Samir!
Can't check now, but I'll do a reinstall when I get home this afternoon

Kind regards,
Jerry Becker

Date: Tue, 4 Aug 2015 03:56:48 -0700

**Comment by pablotothemax** [comment]
Getting this too, works before adding, doesn't after :/
