### ISSUE TITLE
Themes are not working with Telescope v0.22.2 

### ISSUE THREAD

**Issue by cohnen** [montecruiseto/scopemount#8]
There are a lot of UI issues once you update telescope to latest release. Is there something I can do to fix this? Do you plan to release an update soon?
Am I doing something wrong?

**Comment by montecruiseto** [comment]
I updated all the themes to v.0.22.2 this weekend, so should be good.
Don't forget to run `meteor update`too.
If still bugs can you post them here? With screenshots please and in different issues if multiple. Thanks!

**Comment by cohnen** [comment]
On your package dependencies still is mentioned 0.21.1 
Here you can just check a live sample http://ixigo.meteor.com with Palomar theme. (Actually same issue is with other themes) I'm using there the last telescope and last theme version. It looks some CSS issue and also titles are coming empty. 

By the way thanks a lot ;)

<img width="1306" alt="screen shot 2015-08-07 at 10 16 45 am" src="https://cloud.githubusercontent.com/assets/2776023/9128942/2525a512-3cee-11e5-88ca-cfcc7d516148.png">
<img width="1414" alt="screen shot 2015-08-07 at 10 16 38 am" src="https://cloud.githubusercontent.com/assets/2776023/9128941/25239f2e-3cee-11e5-99cc-233f356f65ad.png">

**Comment by montecruiseto** [comment]
ok I'll try to fix that this weekend

**Comment by cohnen** [comment]
Sure! Thanks a lot.

Let me know if I you need more info from my side or some help on this.

Regards.

On Fri, Aug 7, 2015 at 3:32 PM, Samir notifications@github.com wrote:

> ok I'll try to fix that this weekend
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/montecruiseto/scopemount/issues/8#issuecomment-128661816
> .

## 

_Ernesto Cohnen de la Cámara_
Mobile: +91 88 00 94 5550

**Comment by montecruiseto** [comment]
ok I updated all the dependencies and pushed to gh and atmosphere. Can you check if it fixed the problem?

**Comment by alexeski** [comment]
I am also trying to use the Palomar theme and can confirm that it's not working unfortunately. Here is how I tested: 1) downloaded the sample Telescope project, 2) updated it to latest version, 3) cleared sample posts, 4) changed to grid mode, configure embedly with right thumb size , 5) installed PAlomar theme, 6) try to post some youtube video --> At this point you can clearly see the theme is broken, the css/layout is all messed up. 

I think the theme is really pretty and would love to use. Let me know if you need more info. Super thanks for your attention montecruiseto!

**Comment by cohnen** [comment]
I can confirm it's still not working with last Telescope. It looks like
they have changed something on templating there.
Basic stuff like titles are not rendering.

I've reverted to telescope 0.21 and there everything works like a charm.

Thanks and Regards.

On Mon, Aug 10, 2015 at 10:43 AM, zebrie notifications@github.com wrote:

> I am also trying to use the Palomar theme and can confirm that it's not
> working unfortunately. Here is how I tested: 1) downloaded the sample
> Telescope project, 2) updated it to latest version, 3) cleared sample
> posts, 4) changed to grid mode, configure embedly with right thumb size ,
> 5) installed PAlomar theme, 6) try to post some youtube video --> At this
> point you can clearly see the theme is broken, the css/layout is all messed
> up.
> 
> I think the theme is really pretty and would love to use. Let me know if
> you need more info. Super thanks for your attention montecruiseto!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/montecruiseto/scopemount/issues/8#issuecomment-129302237
> .

## 

_Ernesto Cohnen de la Cámara_
Mobile: +91 88 00 94 5550

**Comment by alexeski** [comment]
I'll wait for a fixed version then. telescope .21 is not anymore possible for me due to customizations based on the new. Thanks for letting me know.

**Comment by DanielGillies** [comment]
I am on gemini and just tried starfire, both are having some issues as well. Just want you to know

**Comment by montecruiseto** [comment]
hey guys...just to let you know the ever so awesome @SachaG has done a [PR](https://github.com/montecruiseto/scopemount/pull/10) for Palomar. I've not tested it, but went ahead and merged it anyways for you guys, and we will try to translate the changes to other themes. We also discussed the feasibility of more detailed migration guides for Telescope releases so that in the future it will be more easy to keep the themes updated and bug free. For the 0.21 and 0.22 releases, there were some changes which had not been described fully in the release notes and which required deep dives. Also, I simply didnt have that much time lately to really dig deep and stress-testing the theme updates. Any contributions are of course always welcome!

**Comment by cohnen** [comment]
It works like a charm! For Palomar we can close this issue. 

Thanks a lot to both of you! ;)

**Comment by alexeski** [comment]
super thanks to both of you, it's looking awesome now!  Can't wait to see this PR coming :)

Some small issues:

1) The Reply to post comment page is not rendered correctly.  The workaround is to add a custom version of comment_reply.html template, replace class="posts posts-list" by class="posts posts-grid"

2) Upvoting a comment will not change the icon. How could we fix that ?

3) What is the right way to change the upvote icon to a heart?  
And 4) How can I have it become red when clicked?    

I have 3 and 4 working fine on the original Telescope version adding the command Telescope.utils.icons.upvote = "heart"  

Thanks a lot in advance!

**Comment by DanielGillies** [comment]
Okay excellent, I will maybe try to work on fixing one of the themes this weekend depending on how much time i have

**Comment by SachaG** [comment]
@zebrie if you want to override something that's already overridden in a theme, just define it in your own app's code and it'll be loaded after. 

@DanielGillies cool! Don't hesitate to drop by the Slack channel if you have any questions, and to coordinate on what themes to work on :)

**Comment by montecruiseto** [comment]
I tested Laval and pushed an extra fix for the logo colour. This theme should now be completely ok.

@SachaG I tried to run Palomar but I get this error:
![screen shot 2015-08-16 at 14 32 55](https://cloud.githubusercontent.com/assets/10129398/9292490/5022384a-4426-11e5-98cd-9abe32314591.png)

**Comment by SachaG** [comment]
@montecruiseto hmm, does this happen with a fresh Telescope install?

**Comment by montecruiseto** [comment]
Hey guys. Unfortunately I'm discontinuing support on Scopemount but the themes will remain accessible as inspirational showcases for your own designs: http://scopemount.startrack.io/
You are of course free to borrow from them however you see fit, or to keep one or more themes alive through a fork.
