### ISSUE TITLE
Magellan is not being displayed correctly

### ISSUE THREAD

**Issue by claudiojulioferraz** [montecruiseto/scopemount#9]
Magellan ("postComponents") is not being displayed correctly. Does an update broke the package or I am not knowing install? It is not equal to Demo.

_Using Google Translate_.

![captura de tela_2015-08-11_15-24-22](https://cloud.githubusercontent.com/assets/7096023/9206286/3ac9f240-403d-11e5-9750-4912dd460459.png)

**Comment by montecruiseto** [comment]
@claudiojulioferraz @SachaG moving this discussion to #8
